sensors:
  obms:
  
    - name: ublox
      type: usb
      device_path: /dev/f9p_device
      topics:
        - { name: /ublox_gps_node/fix, msg_type: sensor_msgs.msg.NavSatFix }
      launch: ublox_launch

    - name: dummy
      type: usb
      device_path: /dev/f9p_device
      topics:
        - { name: /ublox_gps_node/fix, msg_type: sensor_msgs.msg.NavSatFix }
      launch: ublox_launch

    - name: Novatel PwrPack 7
      type: ethernet
      ip: 192.168.1.147
      topics:
        - { name: /novatel/oem7/inspva, msg_type: sensor_msgs.msg.NavSatFix }
      launch: novatel_launch 

    - name: PacMod
      type: usb
      device_path: /dev/kvaser_pacmod_device
      topics:
        - { name: /pacmod/steering_rpt, msg_type: sensor_msgs.msg.NavSatFix }
      launch: PacMod_launch
      
    - name: xsens
      type: usb
      device_path: /dev/xsens_device 
      topics:
        - { name: /xsens/imu/data, msg_type: sensor_msgs.msg.Imu }
      launch: xsens_launch 

  radars:
    - { name: Passenger front radar, type: ethernet, ip: 192.168.1.4,
        topics: [ { name: /smart_radar/port_targets_pass_front, msg_type: geometry_msgs.msg.Vector3Stamped } ],
        launch: radar_launch }
    - { name: Passenger front side radar, type: ethernet, ip: 192.168.1.5,
        topics: [ { name: /smart_radar/port_targets_front_pass_side, msg_type: geometry_msgs.msg.Vector3Stamped } ],
        launch: radar_launch }
    - { name: Passenger rear side radar, type: ethernet, ip: 192.168.1.6,
        topics: [ { name: /smart_radar/port_targets_pass_rear_side, msg_type: geometry_msgs.msg.Vector3Stamped } ],
        launch: radar_launch }
    - { name: Passenger rear radar, type: ethernet, ip: 192.168.1.7,
        topics: [ { name: /smart_radar/port_targets_pass_rear, msg_type: geometry_msgs.msg.Vector3Stamped } ],
        launch: radar_launch }
    - { name: Driver rear radar, type: ethernet, ip: 192.168.1.8,
        topics: [ { name: /smart_radar/port_targets_driver_rear, msg_type: geometry_msgs.msg.Vector3Stamped } ],
        launch: radar_launch }
    - { name: Driver rear side radar, type: ethernet, ip: 192.168.1.9,
        topics: [ { name: /smart_radar/port_targets_driver_rear_side, msg_type: geometry_msgs.msg.Vector3Stamped } ],
        launch: radar_launch }
    - { name: Driver front side radar, type: ethernet, ip: 192.168.1.10,
        topics: [ { name: /smart_radar/port_targets_driver_front_side, msg_type: geometry_msgs.msg.Vector3Stamped } ],
        launch: radar_launch }
    - { name: Driver front radar, type: ethernet, ip: 192.168.1.11,
        topics: [ { name: /smart_radar/port_targets_driver_front, msg_type: geometry_msgs.msg.Vector3Stamped } ],
        launch: radar_launch }
    - { name: Center front radar, type: ethernet, ip: 192.168.1.12,
        topics: [ { name: /smart_radar/port_targets_front_center, msg_type: geometry_msgs.msg.Vector3Stamped } ],
        launch: radar_launch }

  lidars:
    - name: livox_front
      type: ethernet
      ip: 192.168.1.100
      topics:
        - { name: /livox/lidar/Front/points, msg_type: sensor_msgs.msg.PointCloud2 }
      launch: livox_launch
      
    - name: livox_bumper
      type: ethernet
      ip: 192.168.1.101
      topics:
        - { name: /livox/lidar/Bumper/points, msg_type: sensor_msgs.msg.PointCloud2 }
      launch: livox_launch
      
    - name: livox_right
      type: ethernet
      ip: 192.168.1.102
      topics:
        - { name: /livox/lidar/Right/points, msg_type: sensor_msgs.msg.PointCloud2 }
      launch: livox_launch
      
    - name: livox_left
      type: ethernet
      ip: 192.168.1.103
      topics:
        - { name: /livox/lidar/Left/points, msg_type: sensor_msgs.msg.PointCloud2}
      launch: livox_launch
      
    - name: hesai
      type: ethernet
      ip: 192.168.1.201
      topics:
        - { name: /hesai/lidar/points, msg_type: sensor_msgs.msg.PointCloud2}
      launch: hesai_launch

  cameras:
    - name: Oak_Camera
      type: ethernet
      ip: 192.168.1.226
      topics:
        - { name: /oak/imu/data, msg_type: sensor_msgs.msg.Imu}
      launch: camera_launch

  event_cameras:    
    - name: Event_Camera
      type: usb
      device_path: /dev/prophesee_evk4_device
      topics:
        - { name: /event_camera/events, msg_type: sensor_msgs.msg.Image }
      launch: event_camera_launch

launch_files:
  novatel_launch:
    command: "ros2 launch novatel_oem7_driver oem7_port.launch.py oem7_port_name:=/dev/pwrpak7_device oem7_receiver_log_file:=<bag_experiment>/nova_<timestamp>.gps"
    open_in_terminal: true

  xsens_launch:
    command: "ros2 launch xsens_mti_ros2_driver xsens_mti_node.launch.py"
    open_in_terminal: true

  ublox_launch:
    command: "ros2 launch ublox_gps ublox_gps_node-launch_NavINST.py"
    open_in_terminal: true

  radar_launch:
    command: "ros2 launch umrr_ros2_driver radar.launch.py"
    open_in_terminal: true

  livox_launch:
    command: "ros2 launch livox_ros_driver2 msg_HAP_launch_multi.py"
    open_in_terminal: true

  hesai_launch:
    command: "ros2 launch hesai_ros_driver start.py"
    open_in_terminal: true

  camera_launch:
    command: "ros2 launch depthai_ros_driver camera_oak_d_LR_base.launch.py"
    open_in_terminal: true

  event_camera_launch:
    command: "ros2 launch metavision_driver driver_node.launch.py"
    open_in_terminal: true

  PacMod_launch:
    command: "ros2 launch pacmod3 pacmod3.launch.xml"
    open_in_terminal: true

record_partitions:
  OBMS:
    topics:
      # XSENS remapped topics
      - /xsens/gnss
      - /xsens/gnss_pose
      - /xsens/filter/euler
      - /xsens/filter/free_acceleration
      - /xsens/filter/positionlla
      - /xsens/filter/quaternion
      - /xsens/filter/twist
      - /xsens/filter/velocity
      - /xsens/imu/acceleration
      - /xsens/imu/angular_velocity
      - /xsens/imu/data
      - /xsens/imu/mag
      - /xsens/imu/time_ref
      - /xsens/imu/utctime
      - /xsens/nmea
      - /xsens/pressure
      - /xsens/status
      - /xsens/temperature
      # Other GNSS/IMU topics
      - /imu/rear/data
      - /novatel/oem7/bestgnsspos
      - /novatel/oem7/bestgnssvel
      - /novatel/oem7/bestpos
      - /novatel/oem7/fix
      - /novatel/oem7/gps
      - /novatel/oem7/imu/data
      - /novatel/oem7/inspva
      - /novatel/oem7/inspvax
      - /novatel/oem7/time
      # Ublox topics
      - /ublox_gps_node/aidalm
      - /ublox_gps_node/aideph
      - /ublox_gps_node/diagnostics
      - /ublox_gps_node/fix
      - /ublox_gps_node/fix_velocity
      - /ublox_gps_node/monhw
      - /ublox_gps_node/navclock
      - /ublox_gps_node/navcov
      - /ublox_gps_node/navheading
      - /ublox_gps_node/navpvt
      - /ublox_gps_node/navrelposned
      - /ublox_gps_node/navstate
      - /ublox_gps_node/navstatus
      - /ublox_gps_node/navsvin
      - /ublox_gps_node/nmea
      - /ublox_gps_node/parameter_events
      - /ublox_gps_node/rosout
      - /ublox_gps_node/rtcm
      - /ublox_gps_node/rxmrtcm
      
      # PacMod 
      - /pacmod/accel_aux_rpt
      - /pacmod/accel_rpt
      - /pacmod/all_system_statuses
      - /pacmod/brake_aux_rpt
      - /pacmod/brake_rpt
      - /pacmod/component_rpt
      - /pacmod/date_time_rpt
      - /pacmod/enabled
      - /pacmod/global_rpt
      - /pacmod/lat_lon_heading_rpt
      - /pacmod/pacmod/transition_event
      - /pacmod/shift_aux_rpt
      - /pacmod/shift_rpt
      - /pacmod/steering_aux_rpt
      - /pacmod/steering_rpt
      - /pacmod/turn_aux_rpt
      - /pacmod/turn_rpt
      - /pacmod/vehicle_speed_rpt
      - /pacmod/vin_rpt
      - /pacmod/wheel_speed_rpt
      - /pacmod/yaw_rate_rpt


      # Livox IMUs
      - /livox/lidar/Bumper/imu
      - /livox/lidar/Front/imu
      - /livox/lidar/Left/imu
      - /livox/lidar/Right/imu

      #OAK IMU
      - /oak/imu/data


  lidars:
    topics:   
      - /livox/lidar/Bumper/points
      - /livox/lidar/Front/points
      - /livox/lidar/Left/points
      - /livox/lidar/Right/points
      - /hesai/lidar/packets_loss
      - /hesai/lidar/points

  cameras:
    topics:
      - /oak/left/camera_info
      - /oak/left/image_raw/compressed
      - /oak/rgb/camera_info
      - /oak/rgb/image_raw/compressed
      - /oak/right/camera_info
      - /oak/right/image_raw/compressed
      - /event_camera/events

  radars:
    topics:
      - /smart_radar/port_targets_driver_front
      - /smart_radar/port_targets_driver_front_side
      - /smart_radar/port_targets_driver_rear
      - /smart_radar/port_targets_driver_rear_side
      - /smart_radar/port_targets_front_center
      - /smart_radar/port_targets_front_pass_side
      - /smart_radar/port_targets_pass_front
      - /smart_radar/port_targets_pass_rear
      - /smart_radar/port_targets_pass_rear_side


